config/routes.rb
Rails.application.routes.draw do
  root to: 'cabs#index'
  constraints format: :json do
    resources :trips
    resources :cabs
  end
  match '*path', to: 'application#page_not_found', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cab.rb
class Cab < ApplicationRecord

  def find_distance(a1, b1, a2, b2)
    ((a2 - a1)**2 + (b2 - b1)**2)**0.5
  end

  def assign
    update(is_assigned: true)
  end

  def trip_end(end_latitude, stop_longitude)
    #Should be available at the drop location once the trip ends.
    update(is_assigned: false, latitude: end_latitude, longitude: stop_longitude)
  end

  class << self
    def find_nearest_cab(start_latitude, start_longitude, is_pink)
      conditions = {}
      conditions[:is_pink] = true if is_pink == true
      cabs = Cab.is_not_assigned(conditions)
      Cab.distance_between?(cabs, start_latitude, start_longitude) if cabs.present?
    end

    def distance_between?(cabs, start_latitude, start_longitude)
      cabs.inject do |cab1, cab2|
        cab1.find_distance(start_latitude, start_longitude, cab1.latitude, cab1.longitude) < cab2.find_distance(start_latitude, start_longitude, cab2.latitude, cab2.longitude) ? cab1 : cab2
      end
    end

    def is_not_assigned(conditions = {})
      conditions[:is_assigned] = false
      where(conditions)
    end
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  PERKM = 1
  PERMINUTE = 2
  PINK = 5
  attr_accessor :is_pink
  belongs_to :cab
  after_create :assign_cab
  before_validation :get_cab, if: :new_record?

  def get_cab
    cab = Cab.find_nearest_cab(self.start_latitude.to_f, self.start_longitude.to_f, self.is_pink)
    if cab.present?
      self.start_time = Time.zone.now
      self.cab = cab
    else
      errors.add(:cab, :blank, message: "Cabs are not available")
    end
  end

  def assign_cab
    self.cab.assign
  end

  def travel_cost(end_latitude, stop_longitude)
    cab = self.cab
    cab.trip_end(end_latitude, stop_longitude)
    trip_cost
  end

  def trip_cost
    time = trip_time
    distance = cab.find_distance(end_latitude, stop_longitude, self.start_latitude, self.start_longitude)
    cost = time*1 +  distance*2
    cost = cost + 5 if self.cab.is_pink
    return distance, time, cost
  end

  def trip_time
    (end_time - start_time)/60
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  rescue_from ::ActiveRecord::RecordNotFound, with: :record_not_found


  def page_not_found
    redirect_to "/"
  end

  protected

  def record_not_found(e)
    render json: { error: e.message }, status: :not_found
  end
end

app/controllers/cabs_controller.rb
class CabsController < ApplicationController
  before_action :set_cab, only: [:show, :edit, :update, :destroy]

  # GET /cabs
  # GET /cabs.json
  def index
    @cabs = Cab.is_not_assigned
  end

  # GET /cabs/1
  # GET /cabs/1.json
  def show
  end

  # GET /cabs/new
  def new
    @cab = Cab.new
  end

  # GET /cabs/1/edit
  def edit
  end

  # POST /cabs
  # POST /cabs.json
  def create
    @cab = Cab.new(cab_params)

    respond_to do |format|
      if @cab.save
        format.html { redirect_to @cab, notice: 'Cab was successfully created.' }
        format.json { render :show, status: :created, location: @cab }
      else
        format.html { render :new }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabs/1
  # PATCH/PUT /cabs/1.json
  def update
    respond_to do |format|
      if @cab.update(cab_params)
        format.html { redirect_to @cab, notice: 'Cab was successfully updated.' }
        format.json { render :show, status: :ok, location: @cab }
      else
        format.html { render :edit }
        format.json { render json: @cab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabs/1
  # DELETE /cabs/1.json
  def destroy
    @cab.destroy
    respond_to do |format|
      format.html { redirect_to cabs_url, notice: 'Cab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cab
    @cab = Cab.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cab_params
    params.require(:cab).permit(:reg_number, :is_assigned, :latitude, :longitude, :is_pink)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    errors = []
    errors << 'start_latitude reuiqred' if params['trip']['start_latitude'].blank?
    errors << 'start_longitude reuiqred' if params['trip']['start_longitude'].blank?
    if errors.blank?
      @trip = Trip.new(trip_params)
      if @trip.save
        render :show, status: :created
      else
        render json: { message: @trip.errors }, status: :unprocessable_entity
      end
    else
      render json: { message: errors }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    errors = []
    end_latitude = params['trip']['end_latitude'].to_f
    stop_longitude = params['trip']['stop_longitude'].to_f
    errors << 'end_latitude reuiqred' if end_latitude.blank?
    errors << 'stop_longitude reuiqred' if stop_longitude.blank?
    distance, time, cost =  @trip.travel_cost(end_latitude, stop_longitude)
    if errors.blank?
      if @trip.update(end_latitude: end_latitude, stop_longitude: stop_longitude, end_time: Time.zone.now, trip_distance: distance, cost: cost, trip_time: time)
        render :show, status: :ok
      else
        render json: @trip.errors, status: :unprocessable_entity
      end
    else
      render json: @trip.errors, status: :unprocessable_entity
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trip_params
    params.require(:trip).permit(:start_latitude, :end_latitude, :start_longitude, :stop_longitude, :is_pink)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabs_helper.rb
module CabsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/cabs/_form.html.erb
<%= form_for(cab) do |f| %>
  <% if cab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cab.errors.count, "error") %> prohibited this cab from being saved:</h2>

      <ul>
      <% cab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reg_number %>
    <%= f.text_field :reg_number %>
  </div>

  <div class="field">
    <%= f.label :is_assigned %>
    <%= f.check_box :is_assigned %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :is_pink %>
    <%= f.check_box :is_pink %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cabs/edit.html.erb
<h1>Editing Cab</h1>

<%= render 'form', cab: @cab %>

<%= link_to 'Show', @cab %> |
<%= link_to 'Back', cabs_path %>

app/views/cabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cabs</h1>

<table>
  <thead>
    <tr>
      <th>Reg number</th>
      <th>Is assigned</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Is pink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabs.each do |cab| %>
      <tr>
        <td><%= cab.reg_number %></td>
        <td><%= cab.is_assigned %></td>
        <td><%= cab.latitude %></td>
        <td><%= cab.longitude %></td>
        <td><%= cab.is_pink %></td>
        <td><%= link_to 'Show', cab %></td>
        <td><%= link_to 'Edit', edit_cab_path(cab) %></td>
        <td><%= link_to 'Destroy', cab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cab', new_cab_path %>

app/views/cabs/new.html.erb
<h1>New Cab</h1>

<%= render 'form', cab: @cab %>

<%= link_to 'Back', cabs_path %>

app/views/cabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reg number:</strong>
  <%= @cab.reg_number %>
</p>

<p>
  <strong>Is assigned:</strong>
  <%= @cab.is_assigned %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @cab.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @cab.longitude %>
</p>

<p>
  <strong>Is pink:</strong>
  <%= @cab.is_pink %>
</p>

<%= link_to 'Edit', edit_cab_path(@cab) %> |
<%= link_to 'Back', cabs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuintypeAssignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= form_for(trip) do |f| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_latitude %>
    <%= f.text_field :start_latitude %>
  </div>

  <div class="field">
    <%= f.label :end_latitude %>
    <%= f.text_field :end_latitude %>
  </div>

  <div class="field">
    <%= f.label :start_longitude %>
    <%= f.text_field :start_longitude %>
  </div>

  <div class="field">
    <%= f.label :stop_longitude %>
    <%= f.text_field :stop_longitude %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :trip_distance %>
    <%= f.text_field :trip_distance %>
  </div>

  <div class="field">
    <%= f.label :cab_id %>
    <%= f.text_field :cab_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Start latitude</th>
      <th>End latitude</th>
      <th>Start longitude</th>
      <th>Stop longitude</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Trip distance</th>
      <th>Cab</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.start_latitude %></td>
        <td><%= trip.end_latitude %></td>
        <td><%= trip.start_longitude %></td>
        <td><%= trip.stop_longitude %></td>
        <td><%= trip.start_time %></td>
        <td><%= trip.end_time %></td>
        <td><%= trip.trip_distance %></td>
        <td><%= trip.cab %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start latitude:</strong>
  <%= @trip.start_latitude %>
</p>

<p>
  <strong>End latitude:</strong>
  <%= @trip.end_latitude %>
</p>

<p>
  <strong>Start longitude:</strong>
  <%= @trip.start_longitude %>
</p>

<p>
  <strong>Stop longitude:</strong>
  <%= @trip.stop_longitude %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @trip.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @trip.end_time %>
</p>

<p>
  <strong>Trip distance:</strong>
  <%= @trip.trip_distance %>
</p>

<p>
  <strong>Cab:</strong>
  <%= @trip.cab %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>